# Generated by Django 3.2.9 on 2022-01-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Marik Channels',
                'db_table': 'marik_channels',
            },
        ),
        migrations.CreateModel(
            name='MavrikApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(max_length=20, unique=True)),
                ('app_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('app_config', models.JSONField(blank=True, default=dict, null=True)),
                ('app_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('allowed_domains', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_channel_types', models.ManyToManyField(blank=True, related_name='app_channels', to='mavrik_apps.ChannelTypes')),
            ],
            options={
                'verbose_name_plural': 'Mavrik Apps',
                'db_table': 'mavrik_apps',
            },
        ),
    ]
