# Generated by Django 3.2.9 on 2022-01-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mavrik_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeltypes',
            options={'verbose_name_plural': 'Marik Channel Types'},
        ),
        migrations.AlterModelTable(
            name='channeltypes',
            table='mavrik_app_channel_types',
        ),
        migrations.CreateModel(
            name='MaverikChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('channel_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('connectivity_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expire'), ('paused', 'Paused'), ('retired', 'Retired'), ('unused', 'Unused'), ('active', 'Active')], default='active', max_length=15)),
                ('connectivity_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_type_set', to='mavrik_apps.channeltypes')),
            ],
            options={
                'verbose_name_plural': 'Marik Channels',
                'db_table': 'mavrik_app_channels',
            },
        ),
    ]
