# Generated by Django 3.2.9 on 2022-01-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_auto_20220118_2321'),
        ('mavrik_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeltypes',
            options={'verbose_name_plural': 'Marik Channel Types'},
        ),
        migrations.AddField(
            model_name='channeltypes',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='channeltypes',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channeltypes',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook')], default='facebook', max_length=20),
        ),
        migrations.AlterField(
            model_name='channeltypes',
            name='channel_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='channeltypes',
            table='mavrik_app_channel_types',
        ),
        migrations.CreateModel(
            name='MaverikChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_name', models.CharField(max_length=100, unique=True)),
                ('channel_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('channel_type', models.CharField(choices=[('facebook_page', 'Facebook Page'), ('facebook_messenger', 'Facebook Messenger'), ('live_chat', 'Live Chat'), ('whatsapp', 'WhatsApp'), ('API', 'API'), ('email', 'Email')], max_length=40)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True)),
                ('connectivity_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expire'), ('paused', 'Paused'), ('retired', 'Retired'), ('unused', 'Unused'), ('inactive', 'Inactive')], default=True, max_length=15)),
                ('connectivity_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail_box', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_mail_box', to='django_mailbox.mailbox')),
            ],
            options={
                'verbose_name_plural': 'Marik Channels',
                'db_table': 'mavrik_app_channels',
            },
        ),
    ]
