# Generated by Django 3.2.9 on 2022-02-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(default=0)),
                ('source_ref', models.IntegerField(default=0)),
                ('ref_id', models.CharField(blank=True, help_text='auto generated with app_id,date,shot_uuid', max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('hold', 'Hold'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='new', max_length=20)),
                ('options', models.CharField(choices=[('allow_attachments', 'Allow Attachments'), ('allow_threaded_replies', 'Allow Threaded Replies'), ('closed_replay', 'Closed Replay')], default='allow_attachments', max_length=50)),
                ('case_tags', models.CharField(blank=True, max_length=20, null=True)),
                ('case_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='low', max_length=20)),
                ('case_type', models.CharField(choices=[('support', 'Support'), ('problem', 'Problem'), ('incident', 'Incident'), ('question', 'Question'), ('task', 'Task')], default='support', max_length=20)),
                ('case_url', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'casex_case_id',
            },
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_aud_id', models.IntegerField(default=0)),
                ('to_aud_id', models.IntegerField(default=0)),
                ('message_type', models.CharField(choices=[('comment', 'Comment'), ('voice', 'Voice'), ('message', 'Message'), ('email', 'Email')], default='message', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('source_ref', models.IntegerField(default=0)),
                ('body', models.TextField(blank=True, null=True)),
                ('plain_body', models.TextField(blank=True, null=True)),
                ('body_format', models.CharField(choices=[('plain', 'Plain'), ('html', 'Html'), ('markdown', 'Markdown')], default='plain', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('attachments', models.JSONField(blank=True, default=dict, null=True)),
                ('via', models.JSONField(blank=True, default=dict, null=True)),
                ('public', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_message', to='casex.caseid')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_message_parent', to='casex.casemessage')),
            ],
            options={
                'db_table': 'casex_case_message',
            },
        ),
        migrations.CreateModel(
            name='CaseAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(blank=True, choices=[('email', 'Email'), ('facebook', 'Facebook'), ('chat', 'Live Chat')], max_length=50, null=True)),
                ('audience_role', models.CharField(blank=True, max_length=50, null=True)),
                ('audience_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_id', models.IntegerField(default=0)),
                ('external_id', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('origin_channel_id', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('access_expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_case_id', to='casex.caseid')),
            ],
            options={
                'db_table': 'casex_case_audience',
            },
        ),
    ]
