version: "3.8"

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - default
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=mevrik.settings
      - SECRET_KEY=w35ty4y5t
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DB_NAME=mevrik_db
      - DB_USER=postgres
      - DB_PASSWORD=mevr1k0909
      - DB_HOST=dc-db-chatbot.mevrik.com
      - DB_PORT=5432
      - MONGO_DB_NAME=
      - MONGO_CONN_STRING=
      - MONGO_USERNAME=
      - MONGO_PASSWORD=
      - MONGO_AUTH_SOURCE=
      - STATIC_DIRECTORY=static
      - STATIC_URL=/static/
      - MEDIA_DIRECTORY=media
      - MEDIA_URL=/media/
      - WIT_KEY=IAKR
      - SENTRY_DSN=
      - REDIS_HOST=
      - REDIS_PORT=
      - REDIS_DB_NUMBER=
      - REDIS_DB_PREFIX=
      - CELERY_RESULT_BACKEND_URL=
      - WIT_KEY=55VK4IVDBQIUSD5DNZP3QBA43EAM33NV
      - APP_URL=localhost:3000
      - CASEX_URL=local.mevrik.com
      - SENTRY_DSN=https://dbe23c8abe084a11893340217d82f138@o1132428.ingest.sentry.io/6181626

networks:
  default:
    driver: bridge
