# Generated by Django 3.2.9 on 2022-02-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='app_name',
            field=models.CharField(default='GP', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
