# Generated by Django 3.2.9 on 2022-02-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_auto_20220208_1243'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='mail_box',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_mail_box', to='django_mailbox.mailbox'),
        ),
        migrations.DeleteModel(
            name='Mailbox',
        ),
    ]
