# Generated by Django 3.2.9 on 2022-02-09 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_mailbox', '0009_auto_20220118_2321'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralloworigin',
            name='app_id',
        ),
        migrations.AddField(
            model_name='useralloworigin',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_allow_origin_app', to='core.apps'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_app', to='core.apps'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='mail_box',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_mail_box', to='django_mailbox.mailbox'),
        ),
        migrations.AlterField(
            model_name='workgroups',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_workgroup', to='core.channels'),
        ),
        migrations.AlterField(
            model_name='workgroups',
            name='user',
            field=models.ManyToManyField(related_name='workgroup_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Mailbox',
        ),
    ]
