# Generated by Django 3.2.9 on 2022-02-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220209_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralloworigin',
            name='app_id',
        ),
        migrations.AddField(
            model_name='useralloworigin',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_allow_origin_app', to='core.apps'),
            preserve_default=False,
        ),
    ]
