# Generated by Django 3.2.9 on 2021-11-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20211129_1354'),
        ('core', '0002_alter_texonomy_texonomy_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Texonomy',
            new_name='Taxonomy',
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='texonomy_type',
            new_name='taxonomy_type',
        ),
    ]
