# Generated by Django 3.2.9 on 2022-02-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220209_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralloworigin',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_allow_origin_app', to='core.apps'),
        ),
    ]
