# Generated by Django 3.2.9 on 2021-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loggedinuserinfo_organization_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
