# Generated by Django 3.2.9 on 2022-01-13 18:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_passwordstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllowOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=50, null=True)),
                ('principal', models.CharField(choices=[('apikey', 'API Key'), ('username', 'User Name')], default='username', max_length=15)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_type', models.CharField(choices=[('referrer', 'Referrer'), ('cidr', 'CIDR'), ('cookie', 'Cookie')], default='cidr', max_length=15)),
                ('origin_sig', models.CharField(blank=True, default='0.0.0.0', max_length=20, null=True)),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2022, 1, 20, 18, 9, 18, 160666))),
                ('allowed', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_allowed_origins',
            },
        ),
    ]
