# Generated by Django 3.2.9 on 2022-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220124_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='app_id',
            field=models.CharField(default='wefrwa', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
