# Generated by Django 3.2.9 on 2022-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220117_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralloworigin',
            name='principal',
            field=models.CharField(choices=[('apikey', 'API Key'), ('username', 'User Name')], default='user', max_length=15),
        ),
    ]
