# Generated by Django 3.2.9 on 2022-01-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavrik_apps', '0001_initial'),
        ('core', '0006_useralloworigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_apps',
            field=models.ManyToManyField(blank=True, related_name='user_apps', to='mavrik_apps.MavrikApps'),
        ),
    ]
