# Generated by Django 3.2.9 on 2021-12-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('app_id', models.CharField(default=0, max_length=244)),
                ('title', models.CharField(blank=True, max_length=244, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=244, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_action', models.CharField(blank=True, max_length=100, null=True)),
                ('action_items', models.JSONField(blank=True, null=True)),
                ('left_contents', models.JSONField(blank=True, null=True)),
                ('display_order', models.CharField(blank=True, max_length=100, null=True)),
                ('content_body', models.JSONField(blank=True, null=True)),
                ('content_format', models.CharField(blank=True, choices=[('JSON', 'json'), ('BASE64', 'base64'), ('TEXT', 'text'), ('MARKDOWN', 'markdown')], max_length=100, null=True)),
                ('template_cache', models.CharField(blank=True, max_length=100, null=True)),
                ('value_cache', models.CharField(blank=True, max_length=244, null=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.content')),
            ],
            options={
                'db_table': 'converse_content',
            },
        ),
        migrations.CreateModel(
            name='ContentCustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ref', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('SETTING', 'setting'), ('FORM', 'form')], default='json', max_length=244)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('field_key', models.CharField(max_length=100)),
                ('field_value', models.CharField(blank=True, max_length=244, null=True)),
                ('validations', models.JSONField(blank=True, null=True)),
                ('choice', models.JSONField(blank=True, null=True)),
                ('editor', models.CharField(choices=[('TEXT', 'text'), ('TEXTAREA', 'textarea'), ('DATE', 'date'), ('DATERANGE', 'daterange'), ('TIME', 'time'), ('TIMERANGE', 'timerange')], default='text', max_length=244)),
                ('editor_config', models.JSONField(blank=True, null=True)),
                ('write_once', models.BooleanField()),
                ('handler', models.CharField(blank=True, max_length=244, null=True)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'converse_content_custom_fields',
            },
        ),
        migrations.CreateModel(
            name='ContentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='image', max_length=100)),
                ('media_ref', models.CharField(default='media/', max_length=244)),
                ('file', models.FileField(upload_to='media/')),
                ('storage_provider', models.CharField(default='local', max_length=100)),
                ('status', models.CharField(default='active', max_length=244)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'converse_content_media',
            },
        ),
        migrations.CreateModel(
            name='ContentTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_type', models.CharField(choices=[('TEXT_GROUP', 'text_group'), ('CATEGORY', 'category'), ('ACTION', 'action')], max_length=100)),
                ('name', models.CharField(max_length=244)),
                ('taxonomy_slug', models.SlugField(max_length=244)),
                ('description', models.TextField()),
                ('display_order', models.CharField(max_length=244)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttaxonomy')),
            ],
            options={
                'db_table': 'converse_content_taxonomy',
            },
        ),
        migrations.CreateModel(
            name='ContentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ref', models.CharField(max_length=244)),
                ('text_vars', models.JSONField(default=dict)),
                ('text_body', models.JSONField(default=dict)),
                ('text_encoding', models.CharField(blank=True, max_length=244, null=True)),
                ('template_type', models.CharField(blank=True, max_length=244, null=True)),
                ('text_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttaxonomy')),
            ],
            options={
                'db_table': 'converse_content_text',
            },
        ),
        migrations.CreateModel(
            name='ConverseContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ref', models.CharField(max_length=100, unique=True)),
                ('type_name', models.CharField(max_length=244)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('config_keys', models.JSONField(blank=True, null=True)),
                ('error_text_ref', models.CharField(blank=True, max_length=244, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'converse_content_type',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=244, null=True)),
                ('app_id', models.CharField(blank=True, max_length=244, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.contenttaxonomy')),
            ],
            options={
                'db_table': 'content_flow',
            },
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=244, null=True)),
                ('node_type', models.CharField(blank=True, choices=[('Start', 'start'), ('Content', 'content')], max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flownodes', to='content.flow')),
                ('initial_content_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.content')),
            ],
            options={
                'db_table': 'content_flow_node',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=244)),
                ('template_code', models.CharField(max_length=244, unique=True)),
                ('template_type', models.CharField(choices=[('message', 'Message'), ('email', 'Email')], default='message', max_length=15)),
                ('template_format', models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('mustache', 'Mustache')], default='text', max_length=15)),
                ('body_template', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_vars', models.JSONField(blank=True, default=dict, null=True)),
                ('value_resolver', models.CharField(blank=True, max_length=255, null=True)),
                ('template_group_id', models.IntegerField(blank=True, default=1, null=True)),
                ('allowed_channel_types', models.JSONField(blank=True, default=dict, null=True)),
                ('attachments', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'In Active'), ('draft', 'Draft')], default='active', max_length=15)),
                ('usage_count', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_message_template',
            },
        ),
        migrations.CreateModel(
            name='NodeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('flow_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.flownode')),
            ],
            options={
                'db_table': 'content_node_contents',
            },
        ),
        migrations.CreateModel(
            name='NodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=244, null=True)),
                ('value', models.JSONField(default=dict)),
                ('flow_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='content.flownode')),
            ],
            options={
                'db_table': 'content_node_config',
            },
        ),
        migrations.CreateModel(
            name='ContentVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_type', models.CharField(max_length=100)),
                ('var_key', models.CharField(max_length=244)),
                ('var_mapping', models.CharField(max_length=244)),
                ('default_value', models.CharField(max_length=100)),
                ('optional', models.CharField(max_length=244)),
                ('params', models.JSONField()),
                ('content_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttext')),
            ],
            options={
                'db_table': 'converse_content_vars',
            },
        ),
        migrations.CreateModel(
            name='ContentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(blank=True, max_length=255, null=True)),
                ('option_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.content')),
            ],
            options={
                'db_table': 'converse_content_options',
            },
        ),
        migrations.CreateModel(
            name='ContentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=244)),
                ('field_value', models.CharField(max_length=100)),
                ('value_format', models.CharField(choices=[('JSON', 'json'), ('BASE64', 'base64'), ('TEXT', 'text'), ('MARKDOWN', 'markdown')], default='json', max_length=100)),
                ('params', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.content')),
                ('field_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contentcustomfields')),
            ],
            options={
                'db_table': 'converse_content_data',
            },
        ),
    ]
