# Generated by Django 3.2.9 on 2021-12-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='app_id',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
