# Generated by Django 3.2.9 on 2022-02-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.taxonomy'),
        ),
        migrations.AddField(
            model_name='contentvars',
            name='content_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttext'),
        ),
        migrations.AddField(
            model_name='contenttext',
            name='text_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttaxonomy'),
        ),
        migrations.AddField(
            model_name='contenttaxonomy',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttaxonomy'),
        ),
        migrations.AddField(
            model_name='contentoptions',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.content'),
        ),
        migrations.AddField(
            model_name='contentdata',
            name='content_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.content'),
        ),
        migrations.AddField(
            model_name='contentdata',
            name='field_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contentcustomfields'),
        ),
        migrations.AddField(
            model_name='content',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_child_set', to='content.content'),
        ),
    ]
