# Generated by Django 3.2.7 on 2021-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ref', models.CharField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('SETTING', 'setting'), ('FORM', 'form')], default='json', max_length=244)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('field_key', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=244)),
                ('validations', models.JSONField()),
                ('choice', models.JSONField()),
                ('editor', models.CharField(choices=[('TEXT', 'text'), ('TEXTAREA', 'textarea'), ('DATE', 'date'), ('DATERANGE', 'daterange'), ('TIME', 'time'), ('TIMERANGE', 'timerange')], max_length=244)),
                ('editor_config', models.JSONField()),
                ('write_once', models.BooleanField()),
                ('handler', models.CharField(max_length=244)),
                ('active', models.CharField(max_length=244)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'converse_content_custom_fields',
            },
        ),
        migrations.CreateModel(
            name='ContentVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_type', models.CharField(max_length=100)),
                ('var_key', models.CharField(max_length=244)),
                ('var_mapping', models.CharField(max_length=244)),
                ('default_value', models.CharField(max_length=100)),
                ('optional', models.CharField(max_length=244)),
                ('params', models.JSONField()),
            ],
            options={
                'db_table': 'converse_content_vars',
            },
        ),
    ]
