# Generated by Django 3.2.9 on 2021-12-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('content', '0002_alter_content_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.taxonomy'),
        ),
    ]
