# Generated by Django 3.2.9 on 2021-12-26 14:14

from django.db import migrations, models
import django.db.models.deletion
import mods.content.models.uploads


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_flow_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(default=0)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, default='Local', max_length=255, null=True)),
                ('filepath', models.FileField(blank=True, null=True, upload_to=mods.content.models.uploads.FileManager.photo_path)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('filemeta', models.JSONField(blank=True, default=dict, null=True)),
                ('variation', models.JSONField(blank=True, default=dict, null=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_uploads',
            },
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='attachments',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='attachment',
            field=models.TextField(default=dict),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='initial_content_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.content'),
        ),
    ]
