# Generated by Django 3.2.9 on 2021-12-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_flow_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownode',
            name='initial_content_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.content'),
        ),
    ]
