# Generated by Django 3.2.7 on 2021-11-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20211104_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcustomfields',
            name='type_ref',
            field=models.CharField(max_length=100),
        ),
    ]
