# Generated by Django 3.2.9 on 2022-01-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20211226_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_child_set', to='content.content'),
        ),
    ]
