# Generated by Django 3.2.7 on 2021-11-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_contentcustomfields_type_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcustomfields',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentcustomfields',
            name='choice',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentcustomfields',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentcustomfields',
            name='editor',
            field=models.CharField(choices=[('TEXT', 'text'), ('TEXTAREA', 'textarea'), ('DATE', 'date'), ('DATERANGE', 'daterange'), ('TIME', 'time'), ('TIMERANGE', 'timerange')], default='text', max_length=244),
        ),
        migrations.AlterField(
            model_name='contentcustomfields',
            name='editor_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentcustomfields',
            name='field_value',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='contentcustomfields',
            name='handler',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='contentcustomfields',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contentcustomfields',
            name='validations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversecontenttype',
            name='content_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversecontenttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversecontenttype',
            name='error_text_ref',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
