# Generated by Django 3.2.7 on 2021-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20211104_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcustomfields',
            name='active',
            field=models.BooleanField(),
        ),
    ]
