# Generated by Django 3.2.9 on 2022-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_content_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttext',
            name='text_ref',
            field=models.CharField(max_length=244, unique=True),
        ),
    ]
