# Generated by Django 3.2.7 on 2021-11-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_contentcustomfields_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttext',
            name='text_group_id',
        ),
        migrations.AddField(
            model_name='contenttext',
            name='text_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttaxonomy'),
        ),
        migrations.AddField(
            model_name='contentvars',
            name='content_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttext'),
        ),
        migrations.AlterField(
            model_name='contentdata',
            name='content_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.content'),
        ),
        migrations.AlterField(
            model_name='contentdata',
            name='field_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contentcustomfields'),
        ),
    ]
