# Generated by Django 3.2.7 on 2021-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20211106_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttaxonomy',
            name='taxonomy_slug',
            field=models.SlugField(max_length=244),
        ),
    ]
