# Generated by Django 3.2.7 on 2021-11-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_contenttaxonomy_taxonomy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmedia',
            name='public_url',
            field=models.FileField(upload_to='media/'),
        ),
    ]
