# Generated by Django 3.2.7 on 2021-11-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_contentmedia_public_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type_ref',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ContentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(blank=True, max_length=255, null=True)),
                ('option_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.content')),
            ],
            options={
                'db_table': 'converse_content_options',
            },
        ),
    ]
