# Generated by Django 3.2.9 on 2021-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
