# Generated by Django 3.2.9 on 2021-11-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20211124_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfig',
            name='flow_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodeconfigs', to='content.flownode'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='key',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='value',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
