# Generated by Django 3.2.9 on 2021-11-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20211125_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttext',
            name='error_text_ref',
        ),
        migrations.RemoveField(
            model_name='contenttext',
            name='has_vars',
        ),
        migrations.RemoveField(
            model_name='contenttext',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='contenttext',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='contenttext',
            name='text_vars',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='template_type',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='text_body',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='text_encoding',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
