# Generated by Django 3.2.9 on 2021-11-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20211128_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_body',
            field=models.JSONField(),
        ),
    ]
