# Generated by Django 3.2.9 on 2021-11-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_texonomy_texonomy_type'),
        ('content', '0016_auto_20211128_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=244, unique=True)),
                ('template_type', models.CharField(choices=[('message', 'message'), ('email', 'email')], default='', max_length=15)),
                ('template_format', models.CharField(choices=[('text', 'text'), ('markdown', 'markdown')], default='', max_length=15)),
                ('body_template', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_var', models.TextField(blank=True, null=True)),
                ('value_resolver', models.CharField(blank=True, max_length=255, null=True)),
                ('app_id', models.IntegerField(default=0)),
                ('allowed_channel_types', models.CharField(choices=[('live-chat', 'Live Chat'), ('messanger', 'Messanger'), ('comment', 'Comment')], default='', max_length=15)),
                ('attachment', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'In Active'), ('draft', 'Draft')], default='', max_length=15)),
                ('usage_count', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.texonomy')),
            ],
            options={
                'db_table': 'content_message_template',
            },
        ),
    ]
