# Generated by Django 3.2.9 on 2021-11-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_messagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttext',
            name='text_body',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='text_vars',
            field=models.JSONField(default=dict),
        ),
    ]
