# Generated by Django 3.2.9 on 2021-11-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_content_content_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttext',
            name='text_group',
        ),
    ]
