# Generated by Django 3.2.9 on 2021-11-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20211128_1753'),
        ('content', '0018_remove_contenttext_text_group'),
    ]

    operations = [
    ]
