# Generated by Django 3.2.9 on 2021-11-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_merge_20211129_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttext',
            name='text_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttaxonomy'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='allowed_channel_types',
            field=models.CharField(choices=[('live-chat', 'Live Chat'), ('messenger', 'Messenger'), ('comment', 'Comment')], default='', max_length=15),
        ),
    ]
