# Generated by Django 3.2.9 on 2021-12-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20211130_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='app_id',
            field=models.CharField(default=0, max_length=244),
        ),
    ]
