# Generated by Django 3.2.9 on 2021-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_content_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='template_group',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='template_group_id',
            field=models.IntegerField(default=0),
        ),
    ]
