# Generated by Django 3.2.9 on 2021-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20211201_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='action_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_format',
            field=models.CharField(blank=True, choices=[('JSON', 'json'), ('BASE64', 'base64'), ('TEXT', 'text'), ('MARKDOWN', 'markdown')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='default_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='display_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='left_contents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='subtitle',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='template_cache',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='type_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='value_cache',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
