# Generated by Django 3.2.9 on 2021-11-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('source', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram')], default='', max_length=15)),
                ('page_id', models.CharField(max_length=60)),
                ('page_access_token', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
    ]
