# Generated by Django 3.2.9 on 2022-02-08 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('source', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram')], default='', max_length=15)),
                ('page_id', models.CharField(max_length=60)),
                ('page_access_token', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('messaging', 'messaging'), ('status', 'status'), ('post', 'post'), ('comment', 'comment'), ('reaction', 'reaction')], default='', max_length=15)),
                ('platform', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('whatsapp', 'whatsapp'), ('web', 'web')], default='', max_length=15)),
                ('source', models.CharField(max_length=200)),
                ('content_id', models.CharField(default='', max_length=200)),
                ('body', models.TextField(default='')),
                ('body_parsed', models.TextField(default='')),
                ('from_type', models.CharField(choices=[('psid', 'psid'), ('mevrik_id', 'mevrik_id')], default='', max_length=15)),
                ('from_ref', models.CharField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('from_photo', models.TextField()),
                ('received_at', models.CharField(max_length=50)),
                ('case_id', models.CharField(max_length=50)),
                ('case_message_id', models.CharField(max_length=50)),
                ('message_direction', models.CharField(max_length=50)),
                ('recipient_ref', models.CharField(max_length=50)),
                ('sent_at', models.CharField(max_length=50)),
                ('reply_to_ref', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('app', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('notify', 'notify'), ('callback', 'callback'), ('push', 'push'), ('response', 'response')], max_length=10)),
                ('topic', models.CharField(choices=[('message', 'message'), ('queue', 'queue'), ('profile', 'profile'), ('tag', 'tag')], max_length=10)),
                ('action', models.CharField(choices=[('post', 'post'), ('del', 'del'), ('reply', 'reply'), ('history', 'history')], max_length=10)),
                ('summary', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('callback', models.JSONField(default=dict)),
                ('target', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
