# Generated by Django 3.2.9 on 2021-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('messaging', 'messaging'), ('status', 'status'), ('post', 'post'), ('comment', 'comment'), ('reaction', 'reaction')], default='', max_length=15)),
                ('platform', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('whatsapp', 'whatsapp'), ('web', 'web')], default='', max_length=15)),
                ('source', models.CharField(max_length=200)),
                ('from_type', models.CharField(choices=[('psid', 'psid'), ('mevrik_id', 'mevrik_id')], default='', max_length=15)),
                ('from_ref', models.CharField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('from_photo', models.TextField()),
                ('received_at', models.CharField(max_length=50)),
                ('case_id', models.CharField(max_length=50)),
                ('case_message_id', models.CharField(max_length=50)),
                ('message_direction', models.CharField(max_length=50)),
                ('recipient_ref', models.CharField(max_length=50)),
                ('sent_at', models.CharField(max_length=50)),
                ('reply_to_ref', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
