# Generated by Django 3.2.9 on 2022-01-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(default=0)),
                ('topic', models.CharField(choices=[('social', 'Social'), ('email', 'Email'), ('live_chat', 'Live_Chat'), ('live_call', 'Live_Call'), ('support', 'Support')], default='social', max_length=20)),
                ('strict_source', models.CharField(default='', max_length=100)),
                ('push_direction', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO')], default='fifo', max_length=20)),
                ('escalation_timeout', models.IntegerField(default=0)),
                ('dispute_timeout', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('paused', 'PAUSED'), ('closed', 'CLOSED'), ('retired', 'RETIRED')], default='fifo', max_length=20)),
                ('last_open_at', models.DateTimeField(blank=True, null=True)),
                ('last_closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mevrik_queue_topics',
            },
        ),
    ]
