# Generated by Django 3.2.9 on 2022-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuetopics',
            name='strict_source',
        ),
        migrations.AddField(
            model_name='queuetopics',
            name='allowed_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='queuetopics',
            name='dispute_timeout',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='queuetopics',
            name='escalation_timeout',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='queuetopics',
            name='push_direction',
            field=models.CharField(blank=True, choices=[('fifo', 'FIFO'), ('lifo', 'LIFO')], default='fifo', max_length=20),
        ),
        migrations.AlterField(
            model_name='queuetopics',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'OPEN'), ('paused', 'PAUSED'), ('closed', 'CLOSED'), ('retired', 'RETIRED')], default='fifo', max_length=20),
        ),
        migrations.AlterField(
            model_name='queuetopics',
            name='topic',
            field=models.SlugField(choices=[('social', 'Social'), ('email', 'Email'), ('live_chat', 'Live_Chat'), ('live_call', 'Live_Call'), ('support', 'Support')], default='social', max_length=40),
        ),
    ]
