# Generated by Django 3.2.9 on 2022-01-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0002_auto_20220119_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetopics',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=20),
        ),
    ]
