# Generated by Django 3.2.9 on 2022-01-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0003_alter_queuetopics_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetopics',
            name='allowed_source',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='queuetopics',
            name='push_direction',
            field=models.CharField(blank=True, choices=[('fifo', 'FIFO'), ('lifo', 'LIFO')], default='fifo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='queuetopics',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=20, null=True),
        ),
    ]
