# Generated by Django 3.2.9 on 2022-01-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0004_auto_20220119_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetopics',
            name='topic',
            field=models.SlugField(default='social', max_length=40),
        ),
    ]
