# Generated by Django 3.2.9 on 2022-01-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0005_alter_queuetopics_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetopics',
            name='app_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='queuetopics',
            name='topic',
            field=models.SlugField(choices=[('social', 'Social'), ('email', 'Email'), ('live_chat', 'Live_Chat'), ('live_call', 'Live_Call'), ('support', 'Support')], default='social', max_length=40),
        ),
    ]
