# Generated by Django 3.2.9 on 2022-01-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0006_auto_20220119_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('topic', models.SlugField(choices=[('social', 'Social'), ('email', 'Email'), ('live_chat', 'Live_Chat'), ('live_call', 'Live_Call'), ('support', 'Support')], default='social', max_length=40)),
                ('serial', models.IntegerField()),
                ('source_ref', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('principle_id', models.IntegerField()),
                ('queue_variant', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('item_subject', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('item_from_ref', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('item_to_ref', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('priority', models.CharField(default='normal', max_length=100)),
                ('status', models.CharField(choices=[('incative', 'Inactive'), ('pending', 'Pending'), ('closed', 'Closed'), ('unattended', 'Unattended'), ('disputed', 'Disputed')], default='unattended', max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
