# Generated by Django 3.2.9 on 2022-01-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0010_alter_queueitems_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitems',
            name='principle_id',
            field=models.IntegerField(default=0),
        ),
    ]
