# Generated by Django 3.2.9 on 2022-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0011_alter_queueitems_principle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetopics',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('paused', 'PAUSED'), ('closed', 'CLOSED'), ('retired', 'RETIRED')], default='open', max_length=20),
        ),
    ]
