# Generated by Django 3.2.9 on 2022-01-20 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0012_alter_queuetopics_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuePrinciples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle_type', models.CharField(choices=[('user', 'User'), ('workgroup', 'Workgroup')], default='user', max_length=20)),
                ('principle_id', models.IntegerField()),
                ('display_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('online', models.CharField(choices=[('agent_present', 'AGENT_PRESENT'), ('agent_not_present', 'AGENT_NOT_PRESENT')], default='agent_not_present', max_length=30)),
                ('last_active_at', models.DateTimeField(default=datetime.datetime(2022, 1, 20, 21, 6, 40, 364687))),
                ('principle_meta', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'mevrik_queue_principles',
            },
        ),
    ]
