# Generated by Django 3.2.9 on 2022-01-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0013_queueprinciples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_active_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 17, 2, 3, 738348)),
        ),
        migrations.AlterField(
            model_name='queueprinciples',
            name='principle_id',
            field=models.IntegerField(unique=True),
        ),
    ]
