# Generated by Django 3.2.9 on 2022-01-23 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0014_auto_20220123_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_active_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 17, 12, 8, 813845)),
        ),
    ]
