# Generated by Django 3.2.9 on 2022-01-23 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0015_alter_queueprinciples_last_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_active_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 17, 13, 41, 922655)),
        ),
    ]
