# Generated by Django 3.2.9 on 2022-01-24 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0016_alter_queueprinciples_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueprinciples',
            name='last_assigned_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_active_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 12, 29, 40, 366374)),
        ),
    ]
