# Generated by Django 3.2.9 on 2022-01-24 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0017_auto_20220124_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitems',
            name='principle_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_active_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 12, 31, 37, 107653)),
        ),
    ]
