# Generated by Django 3.2.9 on 2022-01-24 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0020_auto_20220124_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalqueueprinciples',
            name='last_active_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 17, 54, 13, 173886)),
        ),
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_active_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 17, 54, 13, 173886)),
        ),
    ]
