# Generated by Django 3.2.9 on 2022-01-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0021_auto_20220124_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalqueueprinciples',
            name='last_active_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
