# Generated by Django 3.2.9 on 2022-01-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0023_auto_20220124_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalqueueitems',
            name='dispute_timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalqueueitems',
            name='escalation_timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queueitems',
            name='dispute_timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queueitems',
            name='escalation_timeout',
            field=models.IntegerField(default=0),
        ),
    ]
