# Generated by Django 3.2.9 on 2022-01-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_service', '0024_auto_20220125_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalqueueprinciples',
            name='last_active_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalqueueprinciples',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_active_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='queueprinciples',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
