# Generated by Django 3.2.9 on 2021-12-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseid',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='caseid',
            name='ref_id',
            field=models.CharField(blank=True, help_text='auto generated with app_id,date,shot_uuid', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(default=0)),
                ('from_aud_id', models.IntegerField(default=0)),
                ('to_aud_id', models.IntegerField(default=0)),
                ('message_type', models.CharField(choices=[('comment', 'Comment'), ('voice', 'Voice'), ('message', 'Message'), ('email', 'Email')], default='message', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('source_ref', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('plain_body', models.TextField()),
                ('body_format', models.CharField(choices=[('plain', 'Plain'), ('html', 'Html'), ('markdown', 'Markdown')], default='plain', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('attachments', models.JSONField(blank=True, default=dict, null=True)),
                ('via', models.JSONField(blank=True, default=dict, null=True)),
                ('public', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_message_parent', to='caseex.casemessage')),
            ],
            options={
                'db_table': 'caseex_case_message',
            },
        ),
    ]
