# Generated by Django 3.2.9 on 2021-12-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseex', '0002_auto_20211226_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(default=0)),
                ('audience_type', models.CharField(blank=True, max_length=50, null=True)),
                ('audience_role', models.CharField(blank=True, max_length=50, null=True)),
                ('audience_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_id', models.IntegerField(default=0)),
                ('external_id', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('origin_channel_id', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('access_expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_message_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audience_case_message', to='caseex.casemessage')),
            ],
            options={
                'db_table': 'caseex_case_audience',
            },
        ),
    ]
