# Generated by Django 3.2.9 on 2021-11-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_auto_20211110_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='content_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
