from .create_user import CreateUserView
from .groups_view import GroupsView
from .core_token_obtain_pair_view import CoreTokenObtainPairView
from .taxonomy_view import TaxonomyCreateUpateView, TaxonomyListOrFilterView, TaxonomyDeleteView
from .taxonomy_type_view import TaxonomyTypeCreateUpateView, TaxonomyTypeListOrFilterView, TaxonomyTypeDeleteView
from .register import RegisterView
